### ISSUE TITLE
Bug: IsSubDirectory

### ISSUE THREAD

**Issue by wahmedswl** [projectkudu/KuduSync.NET#15]
Hi,
   It seems like there is issue in https://github.com/projectkudu/KuduSync.NET/blob/master/KuduSync.NET/FileSystemHelpers.cs#L74

```
public static bool IsSubDirectory(string path1, string path2)
        {
            if (path1 != null && path2 != null)
            {
                path1 = Path.GetFullPath(path1);
                path2 = Path.GetFullPath(path2);
                return path2.StartsWith(path1, StringComparison.OrdinalIgnoreCase);
            }

            return false;
        }
```

I had following hierarchy structure

Source: ```E:\Development\Production-WS\SequelMedFax\build\_PublishedWebsites\SequelMedFax```
Target: ```E:\Development\Production-WS\SequelMedFax\build\_PublishedWebsites\SequelMedFax_Latest```

And it was giving up error
Source and destination directories cannot be sub-directories of each other
```
https://github.com/projectkudu/KuduSync.NET/blob/5ff87c07d69ed7ce250267d4657c262c89dd547b/KuduSync.NET/KuduSync.cs#L56
```

Thanks

**Comment by davidebbo** [comment]
Yep, that's clearly a bug. :(

Want to take a crack at a PR for a fix? Probably just need to make sure there is a trailing slash on both before comparing.

**Comment by snobu** [comment]
This comparison doesn't look right:

https://github.com/projectkudu/KuduSync.NET/blob/5ff87c07d69ed7ce250267d4657c262c89dd547b/KuduSync.NET/FileSystemHelpers.cs#L80

```csharp
    path1 = Path.GetFullPath(path1);
    path2 = Path.GetFullPath(path2);
    return path2.StartsWith(path1, StringComparison.OrdinalIgnoreCase);
```

`GetFullPath` returns path without trailing `\`

>Return Value
Type: System.String
The fully qualified location of path, such as "C:\MyFile.txt".

Quick and dirty fix just append "\" to inputs.
@wahmedswl, up for it?

**Comment by snobu** [comment]
So `\` works on Mono but depending how you feed it in it may break, since that's the escape char in Linux world.

My suggestion is for:

```csharp
    char separator = Path.DirectorySeparatorChar;
```
Then just append that to `path1` and `path2`.

```bash
snobu@Marvin:~$ mono IsSubDirectory.exe /home /homesomething
DirectorySeparatorChar is /
Comparing /home to /homesomething
IsSubDirectory? -- True

snobu@Marvin:~$ mono IsSubDirectory.exe /home/ /homesomething/
DirectorySeparatorChar is /
OS: Unix 4.4.0.38
Comparing /home/ to /homesomething/
IsSubDirectory? -- False
```

**Comment by davidebbo** [comment]
I think it doesn't matter what char you append, as long as it's a char that's not valid in file names. Its only purpose is to act as a 'stop' to fix the `StartsWith`. Right?

**Comment by snobu** [comment]
That is correct, but i've just remembered that `\` is completely valid character for file names on Linux.
Which could be dangerous.

```
$ touch A\ strange\ file.txt
$ ls -l A*
-rw-rw-r-- 1 snobu snobu    0 nov  2 16:48 A strange file.txt
```

**Comment by davidebbo** [comment]
You can always append both slashes to each path :)

**Comment by snobu** [comment]
I'm submitting a RFC for Emoji as path separators in POSIX. I see no drawbacks for this one: :seedling:

**Comment by snobu** [comment]
Fixed in PR https://github.com/projectkudu/KuduSync.NET/pull/16

**Comment by davidebbo** [comment]
It's on NuGet as v1.3.1.
