### ISSUE TITLE
Results seem pretty random

### ISSUE THREAD

**Issue by nul800sebastiaan** [projectkudu/KuduSync.NET#9]
We've been using this as part of Kudu for a while now and are seeing some pretty random results.

```
λ git push origin master                                                                                                     
Counting objects: 11, done.                                                                                                  
Delta compression using up to 8 threads.                                                                                     
Compressing objects: 100% (6/6), done.                                                                                       
Writing objects: 100% (6/6), 569 bytes | 0 bytes/s, done.                                                                    
Total 6 (delta 4), reused 0 (delta 0)                                                                                        
remote: Updating branch 'master'.                                                                                            
remote: Updating submodules.                                                                                                 
remote: Preparing deployment for commit id '3da1f2f573'.                                                                     
remote: Generating deployment script.                                                                                        
remote: Running deployment command...                                                                                        
remote: Handling Basic Web Site deployment.                                                                                  
remote: KuduSync.NET from: 'C:\inetpub\temp\DWASFiles\Sites\34bac22d-7511-4fd8-bd31-4b2946142e94\VirtualDirectory0\site\repos
itory' to: 'C:\inetpub\temp\DWASFiles\Sites\34bac22d-7511-4fd8-bd31-4b2946142e94\VirtualDirectory0\site\wwwroot'             
remote: Copying file: 'Web.config'                                                                                           
remote: Copying file: 'css\rtebase.css'                                                                                      
remote: Copying file: 'data\Revision\documenttypes\GlobalSettings.courier'                                                   
remote: Copying file: 'images\bg_texture-white-35@2x.png'                                                             
remote: Copying file: 'images\bg\bg_button-middle.png'                                                                       
```

The only file that I had touched and committed to git in this case was `data\Revision\documenttypes\GlobalSettings.courier`.

Checked the KuduSync.NET solution to see how it does the file compare, it's here:
https://github.com/projectkudu/KuduSync.NET/blob/master/KuduSync.NET/KuduSync.cs#L177

However, comparing the LastWriteTimeUtc between repository and wwwroot shows the exact same date/time. These files still got copied again on the next deploy though.
I also checked the attributes on these files and they only have the Archive attribute set, so no difference there. I even downloaded both files and compared their hashes, which are exactly the same.
In these cases the files were added to the `deployments\GUID\manifest` file correctly, so it presumably doesn't detect them as new files needing to be copied over.

Then I added a new .txt file in the root and suddenly 3300+ files get copied from repository > wwwroot (that's basically all the files).
Then I added another new .txt file in the root and only that file + web.config gets copied.

Have you seen similar issues? Most of all, we want to prevent those cases where 3300+ files are getting copied as it could take a long time and it's completely unnecessary.

Let me know if you need any more information or if I can test more scenario's to help debug.

**Comment by amitapl** [comment]
Which hosting environment are you using?

From this path `C:\inetpub\temp\DWASFiles\Sites\34bac22d-7511-4fd8-bd31-4b2946142e94\VirtualDirectory0\site\repos` it doesn't look like Azure.

**Comment by nul800sebastiaan** [comment]
Indeed, we're using Azure Pack which relies on Kudu and KuduSync.NET.

**Comment by amitapl** [comment]
As you've seen in the code, the scenario you're describing is highly unlikely.

Can you use a custom deployment script and print out the LastWriteTime of all files in both source and destination to show this scenario?

You can get your deployment script from the root of the scm site in the **Tools** --> **Download deployment script**, add both files to your repo root and update the deploy.cmd file with the custom steps.

To make this simpler and isolate the issue, you can just run the KuduSync command regardless of deployment.

**Comment by nul800sebastiaan** [comment]
Thanks @amitapl ! I've been testing today with a custom build of KuduSync.NET that adds some more verbose logging when datestamps differ and am now having trouble reproducing the error.

One thing I did find is that the files mentioned above do get touched in wwwroot. So I understand now why they would be redeployed.

I did find one other suspicious part of the code here: 
https://github.com/projectkudu/KuduSync.NET/blob/master/KuduSync.NET/KuduSync.cs#L194
The comment says that a directory will only be deleted if it was in the previous manifest, except the previous manifest is never checked. Is it just a misleading code comment (copied from line 152/153/154)? If not why isn't the previous manifest checked?

**Comment by amitapl** [comment]
Thanks for the CR :)

This is where we verify in the manifest: https://github.com/projectkudu/KuduSync.NET/blob/9a8138d22a8031aec60a8be13018f03a1d287be3/KuduSync.NET/KuduSync.cs#L230

Anyway from what you say I can understand that the re is no issue and it is by design as the files were in fact touched and so were copied over from the source.
